codecov:
  allow_coverage_offsets: True
  
  comment:
    layout: "header, diff, flags, components"

  component_management:
    individual_components:
      - component_id: scilpy_scripts
        name: Scripts
        paths:
          - scripts/
      - component_id: scilpy_library
        name: Library
        paths:
          - scilpy/

  status:
    project:
      default:
        target: 75%
        threshold: 2%
        branches: 
          - master
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 90%
        branches: 
          - master
        if_ci_failed: error
        only_pulls: false

