name: Merge to master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  development_container:
    uses: AlexVCaron/containers-scilus/.github/workflows/docker-builder.yml@test
    with:
      target: scilus
      tag: dev
      update-latest: false
      scilpy-version: master
      build-system-ref: test
    secrets: inherit
