name: Merge to master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  development_container:
    uses: scilus/containers-scilus/.github/workflows/docker-builder.yml@main
    with:
      target: scilus
      tag: dev
      update-latest: false
      scilpy-version: master
    secrets: inherit
