name: Scilpy test suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  MPLBACKEND: agg
  OPENBLAS_NUM_THREADS: 1

jobs:
  test:
    runs-on: scilus-runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Fetch python version from repository
        id: python-selector
        run: echo ::set-output name=python-version::$(cat .python-version)

      - name: Set up Python for Scilpy
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ steps.python-selector.outputs.python-version }}

      - name: Install non-python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            libblas-dev \
            liblapack-dev \
            libfreetype6-dev \
            libgl1-mesa-dev \
            libgl1-mesa-dri \
            python${{ steps.python-selector.outputs.python-version }}-dev \
            python${{ steps.python-selector.outputs.python-version }}-venv \
            python${{ steps.python-selector.outputs.python-version }}-minimal \
            python${{ steps.python-selector.outputs.python-version }}-tk

      - name: Install Scilpy
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Run tests
        run: |
          pytest --cov-report term-missing:skip-covered

      - name: Upload test reports and coverage to artifacts
        uses: echapmanFromBunnings/upload-artifact@3.0.0
        with:
          name: test-reports
          path: |
            .test_reports/*

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .test_reports/coverage.xml
          flags: unittests
          fail_ci_if_error: true
